version: '3.8'

services:
  web:
    image: python:3.9
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    depends_on:
      - redis

  redis:
    image: "redis:alpine"